### ISSUE TITLE
Approved Proposal gets Expired after completion of time

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/governance2#10]
https://github.com/icon-project/governance2/blob/86fc483ecc8fab0856bec5b38e1e6de5ab780a3d/governance/src/main/java/foundation/icon/governance/Proposal.java#L137-L145

After the completion of the proposal time, if the proposal has been approved, the status is changed to expired. It doesn't allow the proposal creator to wait for the completion of the voting period to receive votes from the maximum number of participants.

**Comment by inwonkim** [comment]
The proposal period has passed, why governance have to wait for a vote?

**Comment by ajaya-man** [comment]
Yeah, it seems that after the voting period ends, the approved proposal is changed to expired status. It has to be applied within the voting period. Not sure, if this feature was intended.

**Comment by inwonkim** [comment]
Yeah, apply proposal within the voting period is intended.

**Comment by sink772** [comment]
@ajaya-man You can refer to the updated design of network proposal system in the following doc.
https://docs.google.com/document/d/1Huk5Dyy4ktYmWEy8pY1L5cE6K8H-UMnVa6o4HVv__K8/edit?usp=sharing
